kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    etcd:
      local:
        imageRepository: ghcr.io/go-riscv
        imageTag: 3.7.0-riscv64
- role: control-plane
- role: control-plane
